### ISSUE TITLE
Unicode mess

### ISSUE THREAD

**Issue by trapd00r** [trapd00r/vidir#4]
When vidir is invoked in a directory with files consisting of characters with a value greater than 127, bad things happen:

![unicode mess](http://devel.japh.se/vidir/vidir-unicode-bug.png)

**Comment by xunam** [comment]
Hello,

I don't know what changed since this issue was marked as closed, but non-ASCII file names are still not handled correctly. More specifically, here is what I observe:

    $ mkdir test
    $ cd test
    $ touch gagné
    $ ls
    gagné
    $ vidir

then the editor shows

        1 ./gagnÃ©

If I change the name, say by turning the first g to uppercase, I get this:

    $ ls
    GagnÃ©

Effectively, the listing which is sent to the editor seems to go through an improper Latin1 to UTF8 conversion. I don't know enough of Perl to understand where this happens and how it can be avoided.

Test using current code (commit 91fd1784c5cbf2feef87b465adc3234696bd5815) with Perl version 5.30.1 (as of NixOS 20.03).

**Comment by selim13** [comment]
I don't know perl good enough, but it seems the problem is that file names need to be decoded after readdir, as they are byte strings.

Currently, the solution is to use ls for reading files and pipe them into vidir: `ls | vidir -`

**Comment by trapd00r** [comment]
Hi @selim13, with the latest commit, things should work as expected.

**Comment by selim13** [comment]
Hello! Indeed they are.
Thank you!
